In [1]:
import pandas as pd
import numpy as np

In [2]:
temp_df = pd.read_csv("IMDB Dataset.csv")
temp_df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df = temp_df.iloc[:10000]
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [5]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(17)

In [8]:
df.drop_duplicates(inplace=True)

C:\Users\Om\AppData\Local\Temp\ipykernel_9580\3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

np.int64(0)

### Basic Preprocessing

In [10]:
# Remove Tags
import re

def remove_tags(text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', text)
    return cleaned_text

In [11]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\Om\AppData\Local\Temp\ipykernel_9580\2336150696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)

In [12]:
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [13]:
# Lower Case

df['review'] = df['review'].str.lower()

C:\Users\Om\AppData\Local\Temp\ipykernel_9580\3696792431.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].str.lower()

In [14]:
df['review']

0       one of the other reviewers has mentioned that ...
1       a wonderful little production. the filming tec...
2       i thought this was a wonderful way to spend ti...
3       basically there's a family where a little boy ...
4       petter mattei's "love in the time of money" is...
                              ...
9995    fun, entertaining movie about wwii german spy ...
9996    give me a break. how can anyone say that this ...
9997    this movie is a bad movie. but after watching ...
9998    this is a movie that was probably made to ente...
9999    smashing film about film-making. shows the int...
Name: review, Length: 9983, dtype: object

In [15]:
# Remove Stopword
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_Stopword(text):
    filter_review = []
    words = text.split()

    for review in words:
        if review.lower() not in stop_words:
            filter_review.append(review)
    return " ".join(filter_review)

In [16]:
df['review'] = df['review'].apply(remove_Stopword)

C:\Users\Om\AppData\Local\Temp\ipykernel_9580\995587208.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_Stopword)

In [17]:
df['review']

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [18]:
df

                                                 review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [19]:
import gensim

In [20]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [21]:
story = []

for doc in df['review']:
    raw_sent = sent_tokenize(doc)

    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [22]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2
)

In [23]:
model.build_vocab(story)

In [25]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

(5849713, 6186875)

In [26]:
len(model.wv.index_to_key)

31845

In [27]:
def document_vector(doc):
    # Remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis = 0)

In [28]:
document_vector(df['review'].values[0])

array([-0.0405823 ,  0.33283204,  0.15120523, -0.1295614 , -0.00841838,
       -0.41778752,  0.1735033 ,  0.8433029 , -0.22821607, -0.03967758,
       -0.06714642, -0.49977994, -0.00376054,  0.2412895 ,  0.06994292,
       -0.1432526 ,  0.10808501, -0.5205625 ,  0.09718246, -0.6988122 ,
        0.09496062,  0.14515738,  0.1990643 , -0.20294479, -0.2745422 ,
       -0.09880178, -0.22109829, -0.26745337, -0.30490592,  0.06907295,
        0.5185795 ,  0.05257623,  0.06227331, -0.27554616, -0.25036636,
        0.29965022,  0.09010071, -0.42387506, -0.18325508, -0.7754865 ,
        0.13893212, -0.16996484, -0.2640192 , -0.00867248,  0.41483557,
       -0.23312221, -0.3206479 , -0.07564521,  0.1279352 ,  0.30286184,
        0.17695457, -0.34869766, -0.19214125, -0.13901396, -0.3734307 ,
        0.01718675,  0.35372296,  0.16666283, -0.25056213,  0.01857796,
        0.00992428,  0.20776139, -0.1990073 ,  0.05141807, -0.414515  ,
        0.37990308, -0.06966521,  0.19430536, -0.6490544 ,  0.20647305,
       -0.2184044 ,  0.16643055,  0.47826657, -0.06128474,  0.36304098,
       -0.06843539,  0.08546837, -0.11061811, -0.3839753 ,  0.17358527,
       -0.18847859,  0.05102027, -0.517879  ,  0.58513665,  0.03429216,
       -0.2291087 ,  0.05164952,  0.20832965,  0.49175483,  0.10850538,
        0.43885875,  0.0619684 , -0.07441968,  0.05544133,  0.7073457 ,
        0.24553569,  0.16999719, -0.30344653,  0.23128413, -0.08916171],
      dtype=float32)

In [29]:
from tqdm import tqdm

In [46]:
X = []

for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [02:45<00:00, 60.17it/s]

In [47]:
from sklearn.preprocessing import LabelEncoder

lr = LabelEncoder()

y = lr.fit_transform(df['sentiment'])

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [50]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [51]:
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.771156735102654