In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import re

In [2]:
df = pd.read_csv('fake_news.csv')
df.head()

,id,title,author,date,source,url,language,country,topic,category,...,media_types,named_entity_count,char_count,word_count,citation_count,fact_check_verdict,fact_check_source,publication_timestamp,tokens_count,usability_flags
0,1,Government plan to reshape politics sector rev...,Chen Li,2024-10-08,LocalHerald,https://localherald.example/news/0,en,BR,politics,politics,...,"image,video",4,611,96,0,unverified,FactCheck.org,2024-10-08T00:00:00,96,"{""balanced_classes"": true, ""has_metadata"": tru..."
1,2,Government plan to reshape politics sector rev...,Priya Singh,2018-09-29,TrueVoice,https://truevoice.example/news/1,en,BR,politics,politics,...,none,5,1365,170,2,unverified,FactCheck.org,2018-09-29T00:00:00,170,"{""balanced_classes"": true, ""has_metadata"": tru..."
2,3,Government plan to reshape education sector re...,Liam O'Connor,2022-11-16,TrueVoice,https://truevoice.example/news/2,fr,GB,education,education,...,none,3,1392,171,2,true,FactCheck.org,2022-11-16T00:00:00,171,"{""balanced_classes"": true, ""has_metadata"": tru..."
3,4,Government plan to reshape politics sector rev...,Aisha Khan,2019-11-08,EpochView,https://epochview.example/news/3,hi,BR,politics,politics,...,none,3,938,117,1,unverified,NaN,2019-11-08T00:00:00,117,"{""balanced_classes"": true, ""has_metadata"": tru..."
4,5,How to protect yourself from education risks,NaN,2018-09-06,EpochView,https://epochview.example/news/4,hi,AU,education,education,...,"image,video",7,1663,207,3,true,Snopes,2018-09-06T00:00:00,207,"{""balanced_classes"": true, ""has_metadata"": tru..."

In [3]:
df.shape

(20000, 29)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        20000 non-null  int64
 1   title                     20000 non-null  object
 2   author                    18065 non-null  object
 3   date                      20000 non-null  object
 4   source                    20000 non-null  object
 5   url                       20000 non-null  object
 6   language                  20000 non-null  object
 7   country                   20000 non-null  object
 8   topic                     20000 non-null  object
 9   category                  20000 non-null  object
 10  text                      20000 non-null  object
 11  label                     20000 non-null  object
 12  bias                      20000 non-null  object
 13  source_reliability_score  20000 non-null  float64
 14  readability_score         20000 non-null  float64
 15  sentiment_score           20000 non-null  float64
 16  num_shares                20000 non-null  int64
 17  num_comments              20000 non-null  int64
 18  has_media                 20000 non-null  object
 19  media_types               20000 non-null  object
 20  named_entity_count        20000 non-null  int64
 21  char_count                20000 non-null  int64
 22  word_count                20000 non-null  int64
 23  citation_count            20000 non-null  int64
 24  fact_check_verdict        20000 non-null  object
 25  fact_check_source         16025 non-null  object
 26  publication_timestamp     20000 non-null  object
 27  tokens_count              20000 non-null  int64
 28  usability_flags           20000 non-null  object
dtypes: float64(3), int64(8), object(18)
memory usage: 4.4+ MB

In [5]:
df = df.drop(columns=['named_entity_count','char_count','word_count','citation_count','fact_check_verdict','fact_check_source','publication_timestamp','tokens_count','usability_flags','source_reliability_score','readability_score','sentiment_score','num_shares','num_comments'], axis=1)

In [6]:
df.head()

,id,title,author,date,source,url,language,country,topic,category,text,label,bias,has_media,media_types
0,1,Government plan to reshape politics sector rev...,Chen Li,2024-10-08,LocalHerald,https://localherald.example/news/0,en,BR,politics,politics,Tesla warns a shocking link between politics a...,fake,center,yes,"image,video"
1,2,Government plan to reshape politics sector rev...,Priya Singh,2018-09-29,TrueVoice,https://truevoice.example/news/1,en,BR,politics,politics,A recent peer-reviewed study published by IMF ...,real,right,no,none
2,3,Government plan to reshape education sector re...,Liam O'Connor,2022-11-16,TrueVoice,https://truevoice.example/news/2,fr,GB,education,education,A recent peer-reviewed study published by FDA ...,real,left,no,none
3,4,Government plan to reshape politics sector rev...,Aisha Khan,2019-11-08,EpochView,https://epochview.example/news/3,hi,BR,politics,politics,A recent peer-reviewed study published by IMF ...,real,left,no,none
4,5,How to protect yourself from education risks,NaN,2018-09-06,EpochView,https://epochview.example/news/4,hi,AU,education,education,A recent peer-reviewed study published by FBI ...,real,right,yes,"image,video"

In [7]:
print(df['source'].value_counts())
print(df['country'].value_counts())

source
RapidBulletin    2036
LocalHerald      2025
EpochView        2014
InsightWeekly    2012
DailyPost        2004
GlobalTimes      1992
CitizenReport    1986
TrueVoice        1982
WorldNewsNow     1982
MetroMirror      1967
Name: count, dtype: int64
country
BR    2074
FR    2034
IN    2011
GB    2010
ZA    1999
NG    1990
US    1984
DE    1975
AU    1965
CA    1958
Name: count, dtype: int64

In [8]:
print(df['language'].value_counts())
print(df['label'].value_counts())
print(df['topic'].value_counts())

language
es    5103
en    5002
hi    5001
fr    4894
Name: count, dtype: int64
label
fake          9216
real          8849
misleading    1935
Name: count, dtype: int64
topic
sports           2075
environment      2074
health           2046
politics         1997
science          1995
entertainment    1993
education        1988
finance          1963
technology       1954
crime            1915
Name: count, dtype: int64

In [9]:
print(df['category'].value_counts())
print(df['media_types'].value_counts())

category
sports           2075
environment      2074
health           2046
politics         1997
science          1995
entertainment    1993
education        1988
finance          1963
technology       1954
crime            1915
Name: count, dtype: int64
media_types
none           12591
image,video     2525
video           2486
image           2398
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           20000 non-null  int64
 1   title        20000 non-null  object
 2   author       18065 non-null  object
 3   date         20000 non-null  object
 4   source       20000 non-null  object
 5   url          20000 non-null  object
 6   language     20000 non-null  object
 7   country      20000 non-null  object
 8   topic        20000 non-null  object
 9   category     20000 non-null  object
 10  text         20000 non-null  object
 11  label        20000 non-null  object
 12  bias         20000 non-null  object
 13  has_media    20000 non-null  object
 14  media_types  20000 non-null  object
dtypes: int64(1), object(14)
memory usage: 2.3+ MB

In [11]:
df.isnull().sum()

id                0
title             0
author         1935
date              0
source            0
url               0
language          0
country           0
topic             0
category          0
text              0
label             0
bias              0
has_media         0
media_types       0
dtype: int64

In [12]:
df['author'] = df['author'].fillna('Unknown')

In [13]:
df['author'].value_counts()

author
Unknown           1935
Daniel Park       1850
Sophia Rossi      1843
Aisha Khan        1828
Miguel Alvarez    1827
Noah Brown        1809
Alex Johnson      1803
Liam O'Connor     1797
Priya Singh       1795
Fatima Noor       1765
Chen Li           1748
Name: count, dtype: int64

In [14]:
df['text'].sample(3)

1596     A recent peer-reviewed study published by Appl...
16665    A recent peer-reviewed study published by UN a...
18778    A recent peer-reviewed study published by Tesl...
Name: text, dtype: object

## Text Cleaning

In [15]:
import re
import nltk
import string
from nltk.corpus import stopwords


stop_words = set(stopwords.words('english'))
puncuation  = string.punctuation

def cleaned_text(text):
    text = text.lower()

    # Remove URLs Tag is exist
    text = re.sub(r'https?://\S+|www\.\S+','', text)

    # Remove Punctuation
    text = text.replace(puncuation, '')

    # Stop word
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

In [16]:
df['text'] = df['text'].apply(cleaned_text)

In [17]:
df['text']

0        tesla warns shocking link politics secret agen...
1        recent peer-reviewed study published imf inves...
2        recent peer-reviewed study published fda denie...
3        recent peer-reviewed study published imf uncov...
4        recent peer-reviewed study published fbi annou...
                               ...
19995    recent peer-reviewed study published cdc uncov...
19996    recent peer-reviewed study published investiga...
19997    recent peer-reviewed study published fda uncov...
19998    recent peer-reviewed study published un reveal...
19999    recent peer-reviewed study published nasa warn...
Name: text, Length: 20000, dtype: object

## Handling Label Data

In [94]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['encoded_label'] = le.fit_transform(df['label'])

## Convert Text into Numbers

In [145]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1,2), min_df = 2) # min_df = 2 means if that word occures less than 2 times so we can avoid that word
X = tfidf.fit_transform(df['text'])
y = df['encoded_label']

In [146]:
for word in list(tfidf.vocabulary_.keys())[:100]:
    if ' ' in word:
        print(word)

tesla warns
warns shocking
shocking link
link politics
politics secret
secret agendas
agendas insiders
insiders say
say this
this shock
shock you
you cdc
cdc reveals
reveals surprising
surprising link
you suggests
suggests shocking
you moderna
moderna denies
denies rare
rare link
you confirms
confirms controversial
controversial link
you eu
eu claims
claims alarming
alarming link
recent peer
peer reviewed
reviewed study
study published
published imf
imf investigates
investigates statistical
statistical evidence
evidence politics
politics reporting
reporting measured
measured changes
changes confidence
confidence intervals
intervals recent
published tesla
tesla denies
denies statistical
published cdc

In [147]:
tfidf.vocabulary_

{'tesla': np.int64(14026),
 'warns': np.int64(14063),
 'shocking': np.int64(14002),
 'link': np.int64(10561),
 'politics': np.int64(13945),
 'secret': np.int64(13998),
 'agendas': np.int64(9213),
 'insiders': np.int64(10535),
 'say': np.int64(13993),
 'this': np.int64(14037),
 'shock': np.int64(14000),
 'you': np.int64(14075),
 'cdc': np.int64(9742),
 'reveals': np.int64(13981),
 'surprising': np.int64(14021),
 'suggests': np.int64(14011),
 'moderna': np.int64(10574),
 'denies': np.int64(10440),
 'rare': np.int64(13973),
 'confirms': np.int64(9767),
 'controversial': np.int64(9777),
 'eu': np.int64(10459),
 'claims': np.int64(9755),
 'alarming': np.int64(9215),
 'tesla warns': np.int64(14036),
 'warns shocking': np.int64(14069),
 'shocking link': np.int64(14003),
 'link politics': np.int64(10568),
 'politics secret': np.int64(13947),
 'secret agendas': np.int64(13999),
 'agendas insiders': np.int64(9214),
 'insiders say': np.int64(10536),
 'say this': np.int64(13994),
 'this shock': np.int64(14038),
 'shock you': np.int64(14001),
 'you cdc': np.int64(14079),
 'cdc reveals': np.int64(9749),
 'reveals surprising': np.int64(13989),
 'surprising link': np.int64(14022),
 'you suggests': np.int64(14095),
 'suggests shocking': np.int64(14017),
 'you moderna': np.int64(14090),
 'moderna denies': np.int64(10579),
 'denies rare': np.int64(10445),
 'rare link': np.int64(13974),
 'you confirms': np.int64(14081),
 'confirms controversial': np.int64(9769),
 'controversial link': np.int64(9778),
 'you eu': np.int64(14083),
 'eu claims': np.int64(10462),
 'claims alarming': np.int64(9756),
 'alarming link': np.int64(9216),
 'recent': np.int64(13975),
 'peer': np.int64(13932),
 'reviewed': np.int64(13991),
 'study': np.int64(14009),
 'published': np.int64(13948),
 'imf': np.int64(10522),
 'investigates': np.int64(10551),
 'statistical': np.int64(14007),
 'evidence': np.int64(10470),
 'reporting': np.int64(13979),
 'measured': np.int64(10572),
 'changes': np.int64(9753),
 'confidence': np.int64(9765),
 'intervals': np.int64(10548),
 'un': np.int64(14039),
 'google': np.int64(10506),
 'uncovers': np.int64(14050),
 'fbi': np.int64(10481),
 'announces': np.int64(9217),
 'apple': np.int64(9227),
 'admits': np.int64(9203),
 'reported': np.int64(13977),
 'numbers': np.int64(10596),
 '6316': np.int64(5767),
 'cases': np.int64(9249),
 '138': np.int64(418),
 'deaths': np.int64(9782),
 '83886': np.int64(7660),
 'views': np.int64(14062),
 'recent peer': np.int64(13976),
 'peer reviewed': np.int64(13933),
 'reviewed study': np.int64(13992),
 'study published': np.int64(14010),
 'published imf': np.int64(13960),
 'imf investigates': np.int64(10528),
 'investigates statistical': np.int64(10558),
 'statistical evidence': np.int64(14008),
 'evidence politics': np.int64(10477),
 'politics reporting': np.int64(13946),
 'reporting measured': np.int64(13980),
 'measured changes': np.int64(10573),
 'changes confidence': np.int64(9754),
 'confidence intervals': np.int64(9766),
 'intervals recent': np.int64(10549),
 'published tesla': np.int64(13968),
 'tesla denies': np.int64(14031),
 'denies statistical': np.int64(10447),
 'published cdc': np.int64(13952),
 'cdc denies': np.int64(9747),
 'published un': np.int64(13969),
 'un denies': np.int64(14044),
 'published google': np.int64(13959),
 'google uncovers': np.int64(10515),
 'uncovers statistical': np.int64(14057),
 'published fbi': np.int64(13957),
 'fbi announces': np.int64(10483),
 'announces statistical': np.int64(9224),
 'published apple': np.int64(13951),
 'apple announces': np.int64(9229),
 'fbi uncovers': np.int64(10490),
 'tesla admits': np.int64(14027),
 'admits statistical': np.int64(9210),
 'intervals reported': np.int64(10550),
 'reported numbers': np.int64(13978),
 'numbers 6316': np.int64(12576),
 '6316 cases': np.int64(5768),
 'cases 138': np.int64(9292),
 '138 deaths': np.int64(419),
 'deaths 83886': np.int64(10322),
 '83886 views': np.int64(7661),
 'fda': np.int64(10492),
 'education': np.int64(10450),
 'interpol': np.int64(10537),
 'world': np.int64(14073),
 'bank': np.int64(9238),
 '9164': np.int64(8377),
 '440': np.int64(3869),
 '1504': np.int64(560),
 'published fda': np.int64(13958),
 'fda denies': np.int64(10497),
 'evidence education': np.int64(10472),
 'education reporting': np.int64(10451),
 'published interpol': np.int64(13961),
 'interpol investigates': np.int64(10543),
 'published world': np.int64(13972),
 'world bank': np.int64(14074),
 'bank investigates': np.int64(9244),
 'apple denies': np.int64(9232),
 'published moderna': np.int64(13963),
 'moderna confirms': np.int64(10578),
 'confirms statistical': np.int64(9774),
 'published eu': np.int64(13956),
 'claims statistical': np.int64(9762),
 'fda admits': np.int64(10493),
 'tesla reveals': np.int64(14033),
 'reveals statistical': np.int64(13988),
 'google investigates': np.int64(10512),
 'numbers 9164': np.int64(13612),
 '9164 cases': np.int64(8378),
 'cases 440': np.int64(9625),
 '440 deaths': np.int64(3870),
 '9395': np.int64(8586),
 '484': np.int64(4391),
 'imf uncovers': np.int64(10531),
 'fda announces': np.int64(10494),
 'moderna suggests': np.int64(10582),
 'suggests statistical': np.int64(14018),
 'tesla announces': np.int64(14028),
 'bank uncovers': np.int64(9247),
 'numbers 9395': np.int64(13694),
 '9395 cases': np.int64(8587),
 'cases 484': np.int64(9673),
 '484 deaths': np.int64(4392),
 'nasa': np.int64(10585),
 '7849': np.int64(7172),
 '413': np.int64(3547),
 'bank suggests': np.int64(9246),
 'un announces': np.int64(14041),
 'tesla suggests': np.int64(14034),
 'un claims': np.int64(14042),
 'un suggests': np.int64(14047),
 'published nasa': np.int64(13964),
 'nasa confirms': np.int64(10589),
 'moderna admits': np.int64(10575),
 'numbers 7849': np.int64(13145),
 '7849 cases': np.int64(7173),
 'cases 413': np.int64(9595),
 '413 deaths': np.int64(3548),
 'finance': np.int64(10503),
 '1058': np.int64(77),
 '296': np.int64(2231),
 'fda warns': np.int64(10502),
 'warns statistical': np.int64(14070),
 'evidence finance': np.int64(10475),
 'finance reporting': np.int64(10504),
 'imf reveals': np.int64(10529),
 'eu suggests': np.int64(10467),
 'cdc suggests': np.int64(9750),
 'google confirms': np.int64(10510),
 'published warns': np.int64(13971),
 'nasa warns': np.int64(10595),
 'numbers 1058': np.int64(10624),
 '1058 cases': np.int64(78),
 'cases 296': np.int64(9466),
 '296 deaths': np.int64(2232),
 'science': np.int64(13995),
 '9324': np.int64(8534),
 '51': np.int64(4676),
 '9602': np.int64(8822),
 'tesla investigates': np.int64(14032),
 'evidence science': np.int64(10478),
 'science reporting': np.int64(13996),
 'fbi investigates': np.int64(10487),
 'apple reveals': np.int64(9234),
 'numbers 9324': np.int64(13674),
 '9324 cases': np.int64(8535),
 'cases 51': np.int64(9692),
 '51 deaths': np.int64(4677),
 'crime': np.int64(9779),
 '5564': np.int64(5083),
 '394': np.int64(3325),
 'nasa reveals': np.int64(10592),
 'evidence crime': np.int64(10471),
 'crime reporting': np.int64(9780),
 'interpol suggests': np.int64(10545),
 'nasa uncovers': np.int64(10594),
 'interpol announces': np.int64(10539),
 'nasa claims': np.int64(10588),
 'fbi warns': np.int64(10491),
 'numbers 5564': np.int64(12303),
 '5564 cases': np.int64(5084),
 'cases 394': np.int64(9574),
 '394 deaths': np.int64(3326),
 '5542': np.int64(5067),
 '400': np.int64(3410),
 'cdc uncovers': np.int64(9751),
 'bank claims': np.int64(9241),
 'published denies': np.int64(13955),
 'apple suggests': np.int64(9235),
 'imf admits': np.int64(10523),
 'bank warns': np.int64(9248),
 'numbers 5542': np.int64(12296),
 '5542 cases': np.int64(5068),
 'cases 400': np.int64(9581),
 '400 deaths': np.int64(3411),
 'technology': np.int64(14023),
 '5239': np.int64(4800),
 '223': np.int64(1338),
 'eu uncovers': np.int64(10468),
 'evidence technology': np.int64(10480),
 'technology reporting': np.int64(14024),
 'fbi suggests': np.int64(10489),
 'fda investigates': np.int64(10498),
 'numbers 5239': np.int64(12194),
 '5239 cases': np.int64(4801),
 'cases 223': np.int64(9386),
 '223 deaths': np.int64(1339),
 'pfizer': np.int64(13934),
 '3948': np.int64(3332),
 '344': np.int64(2772),
 'fbi admits': np.int64(10482),
 'google suggests': np.int64(10514),
 'published pfizer': np.int64(13965),
 'pfizer confirms': np.int64(13938),
 'fbi denies': np.int64(10486),
 'eu admits': np.int64(10460),
 'nasa suggests': np.int64(10593),
 'numbers 3948': np.int64(11689),
 '3948 cases': np.int64(3333),
 'cases 344': np.int64(9519),
 '344 deaths': np.int64(2773),
 'incredible': np.int64(10533),
 'unexpected': np.int64(14060),
 'groundbreaking': np.int64(10517),
 'fbi claims': np.int64(10484),
 'claims incredible': np.int64(9759),
 'incredible link': np.int64(10534),
 'link education': np.int64(10563),
 'education secret': np.int64(10452),
 'eu warns': np.int64(10469),
 'warns surprising': np.int64(14071),
 'you fda': np.int64(14085),
 'fda suggests': np.int64(10500),
 'suggests unexpected': np.int64(14020),
 'unexpected link': np.int64(14061),
 'suggests surprising': np.int64(14019),
 'you world': np.int64(14100),
 'bank reveals': np.int64(9245),
 'reveals unexpected': np.int64(13990),
 'fda confirms': np.int64(10496),
 'confirms groundbreaking': np.int64(9770),
 'groundbreaking link': np.int64(10518),
 'eu confirms': np.int64(10463),
 'confirms rare': np.int64(9772),
 'entertainment': np.int64(10453),
 '5863': np.int64(5350),
 '152': np.int64(574),
 'evidence entertainment': np.int64(10473),
 'entertainment reporting': np.int64(10454),
 'interpol denies': np.int64(10542),
 'google warns': np.int64(10516),
 'numbers 5863': np.int64(12413),
 '5863 cases': np.int64(5351),
 'cases 152': np.int64(9308),
 '152 deaths': np.int64(575),
 'environment': np.int64(10456),
 '6311': np.int64(5761),
 '142': np.int64(477),
 '98567': np.int64(9070),
 'evidence environment': np.int64(10474),
 'environment reporting': np.int64(10457),
 'un warns': np.int64(14049),
 'imf confirms': np.int64(10526),
 'numbers 6311': np.int64(12574),
 '6311 cases': np.int64(5762),
 'cases 142': np.int64(9297),
 '142 deaths': np.int64(478),
 'deaths 98567': np.int64(10432),
 '98567 views': np.int64(9071),
 '4078': np.int64(3497),
 '52': np.int64(4766),
 'pfizer reveals': np.int64(13941),
 'pfizer uncovers': np.int64(13943),
 'un investigates': np.int64(14045),
 'google denies': np.int64(10511),
 'numbers 4078': np.int64(11746),
 '4078 cases': np.int64(3498),
 'cases 52': np.int64(9693),
 '52 deaths': np.int64(4767),
 '7485': np.int64(6842),
 '124': np.int64(274),
 'google announces': np.int64(10508),
 'interpol admits': np.int64(10538),
 'pfizer warns': np.int64(13944),
 'numbers 7485': np.int64(13012),
 '7485 cases': np.int64(6843),
 'cases 124': np.int64(9277),
 '124 deaths': np.int64(275),
 '9117': np.int64(8344),
 '169': np.int64(744),
 'pfizer suggests': np.int64(13942),
 'interpol confirms': np.int64(10541),
 'pfizer claims': np.int64(13937),
 'nasa denies': np.int64(10590),
 'numbers 9117': np.int64(13599),
 '9117 cases': np.int64(8345),
 'cases 169': np.int64(9326),
 '169 deaths': np.int64(745),
 '941': np.int64(8609),
 '129': np.int64(322),
 '62616': np.int64(5726),
 'fda uncovers': np.int64(10501),
 'moderna uncovers': np.int64(10583),
 'fbi confirms': np.int64(10485),
 'imf claims': np.int64(10525),
 'numbers 941': np.int64(13703),
 '941 cases': np.int64(8610),
 'cases 129': np.int64(9282),
 '129 deaths': np.int64(323),
 'deaths 62616': np.int64(10186),
 '62616 views': np.int64(5727),
 '473': np.int64(4255),
 'nasa investigates': np.int64(10591),
 'fbi reveals': np.int64(10488),
 'published admits': np.int64(13949),
 'fda claims': np.int64(10495),
 'pfizer investigates': np.int64(13940),
 'cases 473': np.int64(9661),
 '473 deaths': np.int64(4257),
 '1813': np.int64(874),
 '439': np.int64(3856),
 'interpol uncovers': np.int64(10546),
 'tesla uncovers': np.int64(14035),
 'pfizer announces': np.int64(13936),
 'numbers 1813': np.int64(10888),
 '1813 cases': np.int64(875),
 'cases 439': np.int64(9623),
 '439 deaths': np.int64(3858),
 '241': np.int64(1571),
 'google claims': np.int64(10509),
 'moderna announces': np.int64(10576),
 'published uncovers': np.int64(13970),
 'bank confirms': np.int64(9242),
 'cdc investigates': np.int64(9748),
 'moderna claims': np.int64(10577),
 'cases 241': np.int64(9406),
 '241 deaths': np.int64(1572),
 'sports': np.int64(14004),
 'uncovers unexpected': np.int64(14059),
 'link sports': np.int64(10570),
 'sports secret': np.int64(14006),
 'you imf': np.int64(14087),
 'admits unexpected': np.int64(9212),
 'you apple': np.int64(14078),
 'suggests rare': np.int64(14016),
 'you pfizer': np.int64(14092),
 'announces surprising': np.int64(9225),
 'you interpol': np.int64(14088),
 'you warns': np.int64(14099),
 'apple confirms': np.int64(9231),
 'you google': np.int64(14086),
 'google admits': np.int64(10507),
 '271': np.int64(1922),
 'imf announces': np.int64(10524),
 'interpol reveals': np.int64(10544),
 'un reveals': np.int64(14046),
 'cdc announces': np.int64(9744),
 'nasa announces': np.int64(10587),
 'cases 271': np.int64(9439),
 '271 deaths': np.int64(1924),
 '6584': np.int64(6019),
 '140': np.int64(448),
 'un confirms': np.int64(14043),
 'numbers 6584': np.int64(12680),
 '6584 cases': np.int64(6020),
 'cases 140': np.int64(9295),
 '140 deaths': np.int64(450),
 '6564': np.int64(5992),
 'interpol warns': np.int64(10547),
 'eu denies': np.int64(10464),
 'imf suggests': np.int64(10530),
 'numbers 6564': np.int64(12667),
 '6564 cases': np.int64(5993),
 'cases deaths': np.int64(9741),
 'un admits': np.int64(14040),
 'health': np.int64(10519),
 '6997': np.int64(6388),
 '269': np.int64(1905),
 'evidence health': np.int64(10476),
 'health reporting': np.int64(10520),
 'apple admits': np.int64(9228),
 'nasa admits': np.int64(10586),
 'numbers 6997': np.int64(12829),
 '6997 cases': np.int64(6389),
 'cases 269': np.int64(9436),
 '269 deaths': np.int64(1906),
 '340': np.int64(2737),
 'link crime': np.int64(10562),
 'crime secret': np.int64(9781),
 'confirms incredible': np.int64(9771),
 'reveals groundbreaking': np.int64(13984),
 'you tesla': np.int64(14096),
 'admits incredible': np.int64(9207),
 'uncovers groundbreaking': np.int64(14053),
 'investigates controversial': np.int64(10553),
 'you un': np.int64(14097),
 'confirms surprising': np.int64(9775),
 'announces unexpected': np.int64(9226),
 'warns incredible': np.int64(14067),
 'you reported': np.int64(14093),
 'cases 340': np.int64(9515),
 '340 deaths': np.int64(2739),
 '2447': np.int64(1612),
 '289': np.int64(2153),
 'apple warns': np.int64(9237),
 'you nasa': np.int64(14091),
 'suggests groundbreaking': np.int64(14014),
 'un uncovers': np.int64(14048),
 'uncovers surprising': np.int64(14058),
 'uncovers shocking': np.int64(14056),
 'uncovers controversial': np.int64(14052),
 'bank announces': np.int64(9240),
 'announces groundbreaking': np.int64(9220),
 'numbers 2447': np.int64(11130),
 '2447 cases': np.int64(1613),
 'cases 289': np.int64(9458),
 '289 deaths': np.int64(2155),
 '5153': np.int64(4730),
 '23': np.int64(1417),
 'tesla confirms': np.int64(14030),
 'numbers 5153': np.int64(12169),
 '5153 cases': np.int64(4731),
 'cases 23': np.int64(9393),
 '23 deaths': np.int64(1418),
 '445': np.int64(3920),
 'google reveals': np.int64(10513),
 'cases 445': np.int64(9630),
 '445 deaths': np.int64(3921),
 '5866': np.int64(5352),
 '259': np.int64(1767),
 'eu reveals': np.int64(10466),
 'reveals alarming': np.int64(13982),
 'link science': np.int64(10569),
 'science secret': np.int64(13997),
 'confirms unexpected': np.int64(9776),
 'eu investigates': np.int64(10465),
 'investigates unexpected': np.int64(10560),
 'you fbi': np.int64(14084),
 'investigates groundbreaking': np.int64(10554),
 'announces alarming': np.int64(9218),
 'numbers 5866': np.int64(12414),
 '5866 cases': np.int64(5353),
 'cases 259': np.int64(9425),
 '259 deaths': np.int64(1768),
 'admits shocking': np.int64(9209),
 'link environment': np.int64(10565),
 'environment secret': np.int64(10458),
 'denies unexpected': np.int64(10449),
 'suggests alarming': np.int64(14012),
 'announces controversial': np.int64(9219),
 'warns groundbreaking': np.int64(14066),
 'investigates shocking': np.int64(10557),
 'eu announces': np.int64(10461),
 'announces incredible': np.int64(9221),
 'reveals rare': np.int64(13986),
 'uncovers alarming': np.int64(14051),
 'admits surprising': np.int64(9211),
 'you admits': np.int64(14076),
 'admits alarming': np.int64(9204),
 'uncovers incredible': np.int64(14054),
 'warns alarming': np.int64(14064),
 'confirms shocking': np.int64(9773),
 'investigates alarming': np.int64(10552),
 'moderna reveals': np.int64(10581),
 'reveals incredible': np.int64(13985),
 'confirms alarming': np.int64(9768),
 'imf warns': np.int64(10532),
 'bank denies': np.int64(9243),
 '369': np.int64(3018),
 '323': np.int64(2538),
 'tesla claims': np.int64(14029),
 'cases 323': np.int64(9496),
 '323 deaths': np.int64(2539),
 'cdc warns': np.int64(9752),
 'claims groundbreaking': np.int64(9758),
 'you reveals': np.int64(14094),
 'denies shocking': np.int64(10446),
 'apple uncovers': np.int64(9236),
 'uncovers rare': np.int64(14055),
 '2721': np.int64(1938),
 '487': np.int64(4428),
 'evidence sports': np.int64(10479),
 'sports reporting': np.int64(14005),
 'numbers 2721': np.int64(11238),
 '2721 cases': np.int64(1939),
 'cases 487': np.int64(9676),
 '487 deaths': np.int64(4429),
 '4778': np.int64(4317),
 '355': np.int64(2891),
 'published reveals': np.int64(13966),
 'moderna warns': np.int64(10584),
 'numbers 4778': np.int64(12020),
 '4778 cases': np.int64(4318),
 'cases 355': np.int64(9531),
 '355 deaths': np.int64(2893),
 '5294': np.int64(4847),
 '328': np.int64(2588),
 '9720': np.int64(8929),
 'link entertainment': np.int64(10564),
 'entertainment secret': np.int64(10455),
 'warns unexpected': np.int64(14072),
 'warns rare': np.int64(14068),
 'investigates incredible': np.int64(10555),
 'cases 328': np.int64(9501),
 '328 deaths': np.int64(2590),
 'reveals controversial': np.int64(13983),
 'suggests controversial': np.int64(14013),
 'admits groundbreaking': np.int64(9206),
 'suggests incredible': np.int64(14015),
 'cdc claims': np.int64(9745),
 '4068': np.int64(3482),
 '16': np.int64(660),
 'apple investigates': np.int64(9233),
 'warns controversial': np.int64(14065),
 'investigates surprising': np.int64(10559),
 'interpol claims': np.int64(10540),
 'claims unexpected': np.int64(9764),
 'numbers 4068': np.int64(11740),
 '4068 cases': np.int64(3483),
 'cases 16': np.int64(9316),
 '16 deaths': np.int64(661),
 '1069': np.int64(88),
 '464': np.int64(4156),
 'published claims': np.int64(13953),
 'numbers 1069': np.int64(10628),
 '1069 cases': np.int64(89),
 'cases 464': np.int64(9651),
 '464 deaths': np.int64(4157),
 '404': np.int64(3451),
 'bank admits': np.int64(9239),
 'cases 404': np.int64(9585),
 '404 deaths': np.int64(3452),
 '2288': np.int64(1402),
 '244': np.int64(1601),
 'admits rare': np.int64(9208),
 'numbers 2288': np.int64(11060),
 '2288 cases': np.int64(1403),
 'cases 244': np.int64(9409),
 '244 deaths': np.int64(1603),
 '3188': np.int64(2491),
 '479': np.int64(4329),
 'claims shocking': np.int64(9761),
 'numbers 3188': np.int64(11415),
 '3188 cases': np.int64(2492),
 'cases 479': np.int64(9667),
 '479 deaths': np.int64(4330),
 'published suggests': np.int64(13967),
 'denies controversial': np.int64(10442),
 'you announces': np.int64(14077),
 '6323': np.int64(5777),
 '291': np.int64(2188),
 'denies groundbreaking': np.int64(10443),
 'denies alarming': np.int64(10441),
 'numbers 6323': np.int64(12581),
 '6323 cases': np.int64(5778),
 'cases 291': np.int64(9461),
 '291 deaths': np.int64(2189),
 'apple claims': np.int64(9230),
 '28': np.int64(2038),
 'denies surprising': np.int64(10448),
 'reveals shocking': np.int64(13987),
 'cases 28': np.int64(9448),
 '28 deaths': np.int64(2039),
 '398': np.int64(3375),
 'cases 398': np.int64(9578),
 '398 deaths': np.int64(3376),
 '224': np.int64(1347),

In [168]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [149]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr = LogisticRegression(class_weight='balanced', max_iter=5000)
lr.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=5000)

In [160]:
y_pred = lr.predict(X_test)
accuracy_score(y_test, y_pred)

0.7615

In [161]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1829
           1       0.17      0.37      0.23       390
           2       0.81      0.60      0.69      1781

    accuracy                           0.76      4000
   macro avg       0.66      0.66      0.64      4000
weighted avg       0.84      0.76      0.79      4000

In [162]:
confusion_matrix(y_test, y_pred)

array([[1829,    0,    0],
       [   0,  145,  245],
       [   0,  709, 1072]])

In [164]:
dt = DecisionTreeClassifier(class_weight='balanced')
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced')

In [166]:
y_pred1 = dt.predict(X_test)
accuracy_score(y_test, y_pred1)

0.82125

In [167]:
confusion_matrix(y_test, y_pred1)

array([[1829,    0,    0],
       [   0,   72,  318],
       [   0,  397, 1384]])